namespace Flat_Services_Application
{
    partial class Flat_Management_Lessor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Flat_Management_Lessor));
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuIconButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Setting_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.bunifuPanel5 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.bunifuPanel6 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.bunifuCustomLabel2 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.Chat_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Accept_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Pay_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel7 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.Payment_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Flat_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Home_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.bunifuPanel3.SuspendLayout();
            this.bunifuPanel5.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.bunifuPanel6.SuspendLayout();
            this.bunifuPanel4.SuspendLayout();
            this.bunifuPanel7.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuPanel4);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.ForeColor = System.Drawing.Color.White;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(360, 953);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.bunifuPanel3);
            this.bunifuPanel2.Controls.Add(this.Setting_btn);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel2.Location = new System.Drawing.Point(360, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(1222, 156);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel3.BorderRadius = 0;
            this.bunifuPanel3.BorderThickness = 0;
            this.bunifuPanel3.Controls.Add(this.bunifuIconButton1);
            this.bunifuPanel3.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel3.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = false;
            this.bunifuPanel3.Size = new System.Drawing.Size(1222, 160);
            this.bunifuPanel3.TabIndex = 3;
            // 
            // bunifuIconButton1
            // 
            this.bunifuIconButton1.AllowAnimations = true;
            this.bunifuIconButton1.AllowBorderColorChanges = true;
            this.bunifuIconButton1.AllowMouseEffects = true;
            this.bunifuIconButton1.AnimationSpeed = 200;
            this.bunifuIconButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuIconButton1.BackgroundColor = System.Drawing.Color.FloralWhite;
            this.bunifuIconButton1.BorderColor = System.Drawing.Color.FloralWhite;
            this.bunifuIconButton1.BorderRadius = 1;
            this.bunifuIconButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.bunifuIconButton1.BorderThickness = 1;
            this.bunifuIconButton1.ColorContrastOnClick = 30;
            this.bunifuIconButton1.ColorContrastOnHover = 30;
            this.bunifuIconButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuIconButton1.CustomizableEdges = borderEdges7;
            this.bunifuIconButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuIconButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuIconButton1.Image")));
            this.bunifuIconButton1.ImageMargin = new System.Windows.Forms.Padding(0);
            this.bunifuIconButton1.Location = new System.Drawing.Point(1126, 28);
            this.bunifuIconButton1.Name = "bunifuIconButton1";
            this.bunifuIconButton1.RoundBorders = true;
            this.bunifuIconButton1.ShowBorders = true;
            this.bunifuIconButton1.Size = new System.Drawing.Size(71, 71);
            this.bunifuIconButton1.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.bunifuIconButton1.TabIndex = 0;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(47, 55);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(419, 44);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "FLAT MANAGEMENT";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Setting_btn
            // 
            this.Setting_btn.AllowAnimations = true;
            this.Setting_btn.AllowBorderColorChanges = true;
            this.Setting_btn.AllowMouseEffects = true;
            this.Setting_btn.AnimationSpeed = 200;
            this.Setting_btn.BackColor = System.Drawing.Color.Transparent;
            this.Setting_btn.BackgroundColor = System.Drawing.Color.FloralWhite;
            this.Setting_btn.BorderColor = System.Drawing.Color.FloralWhite;
            this.Setting_btn.BorderRadius = 1;
            this.Setting_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.Setting_btn.BorderThickness = 1;
            this.Setting_btn.ColorContrastOnClick = 30;
            this.Setting_btn.ColorContrastOnHover = 30;
            this.Setting_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.Setting_btn.CustomizableEdges = borderEdges8;
            this.Setting_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Setting_btn.Image = ((System.Drawing.Image)(resources.GetObject("Setting_btn.Image")));
            this.Setting_btn.ImageMargin = new System.Windows.Forms.Padding(0);
            this.Setting_btn.Location = new System.Drawing.Point(1130, 30);
            this.Setting_btn.Name = "Setting_btn";
            this.Setting_btn.RoundBorders = true;
            this.Setting_btn.ShowBorders = true;
            this.Setting_btn.Size = new System.Drawing.Size(71, 71);
            this.Setting_btn.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.Setting_btn.TabIndex = 2;
            // 
            // bunifuPanel5
            // 
            this.bunifuPanel5.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel5.BackgroundImage")));
            this.bunifuPanel5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel5.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel5.BorderRadius = 3;
            this.bunifuPanel5.BorderThickness = 1;
            this.bunifuPanel5.Controls.Add(this.tabControl1);
            this.bunifuPanel5.Controls.Add(this.bunifuPanel6);
            this.bunifuPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel5.Location = new System.Drawing.Point(360, 156);
            this.bunifuPanel5.Name = "bunifuPanel5";
            this.bunifuPanel5.ShowBorders = true;
            this.bunifuPanel5.Size = new System.Drawing.Size(1222, 797);
            this.bunifuPanel5.TabIndex = 2;
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Location = new System.Drawing.Point(47, 226);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1139, 469);
            this.tabControl1.TabIndex = 1;
            // 
            // tabPage1
            // 
            this.tabPage1.Location = new System.Drawing.Point(4, 25);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(1131, 440);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // tabPage2
            // 
            this.tabPage2.Location = new System.Drawing.Point(4, 25);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(1131, 440);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // bunifuPanel6
            // 
            this.bunifuPanel6.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel6.BackgroundImage")));
            this.bunifuPanel6.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel6.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel6.BorderRadius = 3;
            this.bunifuPanel6.BorderThickness = 1;
            this.bunifuPanel6.Controls.Add(this.bunifuButton2);
            this.bunifuPanel6.Controls.Add(this.bunifuButton1);
            this.bunifuPanel6.Controls.Add(this.comboBox2);
            this.bunifuPanel6.Controls.Add(this.comboBox1);
            this.bunifuPanel6.Controls.Add(this.bunifuCustomLabel2);
            this.bunifuPanel6.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel6.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel6.Name = "bunifuPanel6";
            this.bunifuPanel6.ShowBorders = true;
            this.bunifuPanel6.Size = new System.Drawing.Size(1222, 187);
            this.bunifuPanel6.TabIndex = 0;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Add Building";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges9;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(1036, 134);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton2.TabIndex = 4;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Search";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges10;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(472, 88);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(110, 24);
            this.bunifuButton1.TabIndex = 3;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // comboBox2
            // 
            this.comboBox2.Font = new System.Drawing.Font("Century", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Location = new System.Drawing.Point(253, 88);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new System.Drawing.Size(130, 24);
            this.comboBox2.TabIndex = 2;
            this.comboBox2.Text = "Charge Status";
            // 
            // comboBox1
            // 
            this.comboBox1.Font = new System.Drawing.Font("Century", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Location = new System.Drawing.Point(47, 88);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(130, 24);
            this.comboBox1.TabIndex = 1;
            this.comboBox1.Text = "Flat Status";
            // 
            // bunifuCustomLabel2
            // 
            this.bunifuCustomLabel2.Font = new System.Drawing.Font("Century", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel2.Location = new System.Drawing.Point(43, 32);
            this.bunifuCustomLabel2.Name = "bunifuCustomLabel2";
            this.bunifuCustomLabel2.Size = new System.Drawing.Size(100, 23);
            this.bunifuCustomLabel2.TabIndex = 0;
            this.bunifuCustomLabel2.Text = "Flat List";
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.BackgroundColor = System.Drawing.SystemColors.Control;
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.SystemColors.Control;
            this.bunifuPanel4.BorderRadius = 3;
            this.bunifuPanel4.BorderThickness = 1;
            this.bunifuPanel4.Controls.Add(this.Chat_btn);
            this.bunifuPanel4.Controls.Add(this.Accept_btn);
            this.bunifuPanel4.Controls.Add(this.Pay_btn);
            this.bunifuPanel4.Controls.Add(this.bunifuPanel7);
            this.bunifuPanel4.Controls.Add(this.Payment_btn);
            this.bunifuPanel4.Controls.Add(this.Flat_btn);
            this.bunifuPanel4.Controls.Add(this.Home_btn);
            this.bunifuPanel4.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel4.ForeColor = System.Drawing.Color.White;
            this.bunifuPanel4.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.bunifuPanel4.ShowBorders = true;
            this.bunifuPanel4.Size = new System.Drawing.Size(360, 953);
            this.bunifuPanel4.TabIndex = 1;
            // 
            // Chat_btn
            // 
            this.Chat_btn.AllowAnimations = true;
            this.Chat_btn.AllowMouseEffects = true;
            this.Chat_btn.AllowToggling = false;
            this.Chat_btn.AnimationSpeed = 200;
            this.Chat_btn.AutoGenerateColors = false;
            this.Chat_btn.AutoRoundBorders = false;
            this.Chat_btn.AutoSizeLeftIcon = true;
            this.Chat_btn.AutoSizeRightIcon = true;
            this.Chat_btn.BackColor = System.Drawing.Color.Transparent;
            this.Chat_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Chat_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Chat_btn.BackgroundImage")));
            this.Chat_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.ButtonText = "Chat";
            this.Chat_btn.ButtonTextMarginLeft = 0;
            this.Chat_btn.ColorContrastOnClick = 45;
            this.Chat_btn.ColorContrastOnHover = 45;
            this.Chat_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Chat_btn.CustomizableEdges = borderEdges1;
            this.Chat_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Chat_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Chat_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Chat_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Chat_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Chat_btn.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Chat_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.IconLeft = null;
            this.Chat_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Chat_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Chat_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Chat_btn.IconMarginLeft = 11;
            this.Chat_btn.IconPadding = 10;
            this.Chat_btn.IconRight = null;
            this.Chat_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Chat_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Chat_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Chat_btn.IconSize = 25;
            this.Chat_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Chat_btn.IdleBorderRadius = 0;
            this.Chat_btn.IdleBorderThickness = 0;
            this.Chat_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Chat_btn.IdleIconLeftImage = null;
            this.Chat_btn.IdleIconRightImage = null;
            this.Chat_btn.IndicateFocus = false;
            this.Chat_btn.Location = new System.Drawing.Point(0, 694);
            this.Chat_btn.Name = "Chat_btn";
            this.Chat_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.OnDisabledState.BorderRadius = 1;
            this.Chat_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.OnDisabledState.BorderThickness = 1;
            this.Chat_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.OnDisabledState.ForeColor = System.Drawing.SystemColors.Control;
            this.Chat_btn.OnDisabledState.IconLeftImage = null;
            this.Chat_btn.OnDisabledState.IconRightImage = null;
            this.Chat_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.onHoverState.BorderRadius = 1;
            this.Chat_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.onHoverState.BorderThickness = 1;
            this.Chat_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.Chat_btn.onHoverState.IconLeftImage = null;
            this.Chat_btn.onHoverState.IconRightImage = null;
            this.Chat_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.OnIdleState.BorderRadius = 1;
            this.Chat_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.OnIdleState.BorderThickness = 1;
            this.Chat_btn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Chat_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.OnIdleState.IconLeftImage = null;
            this.Chat_btn.OnIdleState.IconRightImage = null;
            this.Chat_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.OnPressedState.BorderRadius = 1;
            this.Chat_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.OnPressedState.BorderThickness = 1;
            this.Chat_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.Control;
            this.Chat_btn.OnPressedState.IconLeftImage = null;
            this.Chat_btn.OnPressedState.IconRightImage = null;
            this.Chat_btn.Size = new System.Drawing.Size(360, 129);
            this.Chat_btn.TabIndex = 7;
            this.Chat_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Chat_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Chat_btn.TextMarginLeft = 0;
            this.Chat_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Chat_btn.UseDefaultRadiusAndThickness = true;
            // 
            // Accept_btn
            // 
            this.Accept_btn.AllowAnimations = true;
            this.Accept_btn.AllowMouseEffects = true;
            this.Accept_btn.AllowToggling = false;
            this.Accept_btn.AnimationSpeed = 200;
            this.Accept_btn.AutoGenerateColors = false;
            this.Accept_btn.AutoRoundBorders = false;
            this.Accept_btn.AutoSizeLeftIcon = true;
            this.Accept_btn.AutoSizeRightIcon = true;
            this.Accept_btn.BackColor = System.Drawing.Color.Transparent;
            this.Accept_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Accept_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Accept_btn.BackgroundImage")));
            this.Accept_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Accept_btn.ButtonText = "Accept Tenant";
            this.Accept_btn.ButtonTextMarginLeft = 0;
            this.Accept_btn.ColorContrastOnClick = 45;
            this.Accept_btn.ColorContrastOnHover = 45;
            this.Accept_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Accept_btn.CustomizableEdges = borderEdges2;
            this.Accept_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Accept_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Accept_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Accept_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Accept_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Accept_btn.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Accept_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.IconLeft = null;
            this.Accept_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Accept_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Accept_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Accept_btn.IconMarginLeft = 11;
            this.Accept_btn.IconPadding = 10;
            this.Accept_btn.IconRight = null;
            this.Accept_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Accept_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Accept_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Accept_btn.IconSize = 25;
            this.Accept_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Accept_btn.IdleBorderRadius = 0;
            this.Accept_btn.IdleBorderThickness = 0;
            this.Accept_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Accept_btn.IdleIconLeftImage = null;
            this.Accept_btn.IdleIconRightImage = null;
            this.Accept_btn.IndicateFocus = false;
            this.Accept_btn.Location = new System.Drawing.Point(0, 559);
            this.Accept_btn.Name = "Accept_btn";
            this.Accept_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.OnDisabledState.BorderRadius = 1;
            this.Accept_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Accept_btn.OnDisabledState.BorderThickness = 1;
            this.Accept_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.OnDisabledState.ForeColor = System.Drawing.SystemColors.Control;
            this.Accept_btn.OnDisabledState.IconLeftImage = null;
            this.Accept_btn.OnDisabledState.IconRightImage = null;
            this.Accept_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.onHoverState.BorderRadius = 1;
            this.Accept_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Accept_btn.onHoverState.BorderThickness = 1;
            this.Accept_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.Accept_btn.onHoverState.IconLeftImage = null;
            this.Accept_btn.onHoverState.IconRightImage = null;
            this.Accept_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.OnIdleState.BorderRadius = 1;
            this.Accept_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Accept_btn.OnIdleState.BorderThickness = 1;
            this.Accept_btn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Accept_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.OnIdleState.IconLeftImage = null;
            this.Accept_btn.OnIdleState.IconRightImage = null;
            this.Accept_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.OnPressedState.BorderRadius = 1;
            this.Accept_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Accept_btn.OnPressedState.BorderThickness = 1;
            this.Accept_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Accept_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.Control;
            this.Accept_btn.OnPressedState.IconLeftImage = null;
            this.Accept_btn.OnPressedState.IconRightImage = null;
            this.Accept_btn.Size = new System.Drawing.Size(360, 129);
            this.Accept_btn.TabIndex = 6;
            this.Accept_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Accept_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Accept_btn.TextMarginLeft = 0;
            this.Accept_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Accept_btn.UseDefaultRadiusAndThickness = true;
            // 
            // Pay_btn
            // 
            this.Pay_btn.AllowAnimations = true;
            this.Pay_btn.AllowMouseEffects = true;
            this.Pay_btn.AllowToggling = false;
            this.Pay_btn.AnimationSpeed = 200;
            this.Pay_btn.AutoGenerateColors = false;
            this.Pay_btn.AutoRoundBorders = false;
            this.Pay_btn.AutoSizeLeftIcon = true;
            this.Pay_btn.AutoSizeRightIcon = true;
            this.Pay_btn.BackColor = System.Drawing.Color.Transparent;
            this.Pay_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Pay_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Pay_btn.BackgroundImage")));
            this.Pay_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.ButtonText = "Payment";
            this.Pay_btn.ButtonTextMarginLeft = 0;
            this.Pay_btn.ColorContrastOnClick = 45;
            this.Pay_btn.ColorContrastOnHover = 45;
            this.Pay_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Pay_btn.CustomizableEdges = borderEdges3;
            this.Pay_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Pay_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Pay_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Pay_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Pay_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Pay_btn.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Pay_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.IconLeft = null;
            this.Pay_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Pay_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Pay_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Pay_btn.IconMarginLeft = 11;
            this.Pay_btn.IconPadding = 10;
            this.Pay_btn.IconRight = null;
            this.Pay_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Pay_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Pay_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Pay_btn.IconSize = 25;
            this.Pay_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Pay_btn.IdleBorderRadius = 0;
            this.Pay_btn.IdleBorderThickness = 0;
            this.Pay_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Pay_btn.IdleIconLeftImage = null;
            this.Pay_btn.IdleIconRightImage = null;
            this.Pay_btn.IndicateFocus = false;
            this.Pay_btn.Location = new System.Drawing.Point(0, 424);
            this.Pay_btn.Name = "Pay_btn";
            this.Pay_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.OnDisabledState.BorderRadius = 1;
            this.Pay_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.OnDisabledState.BorderThickness = 1;
            this.Pay_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.OnDisabledState.ForeColor = System.Drawing.SystemColors.Control;
            this.Pay_btn.OnDisabledState.IconLeftImage = null;
            this.Pay_btn.OnDisabledState.IconRightImage = null;
            this.Pay_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.onHoverState.BorderRadius = 1;
            this.Pay_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.onHoverState.BorderThickness = 1;
            this.Pay_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.Pay_btn.onHoverState.IconLeftImage = null;
            this.Pay_btn.onHoverState.IconRightImage = null;
            this.Pay_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.OnIdleState.BorderRadius = 1;
            this.Pay_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.OnIdleState.BorderThickness = 1;
            this.Pay_btn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Pay_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.OnIdleState.IconLeftImage = null;
            this.Pay_btn.OnIdleState.IconRightImage = null;
            this.Pay_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.OnPressedState.BorderRadius = 1;
            this.Pay_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.OnPressedState.BorderThickness = 1;
            this.Pay_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.Control;
            this.Pay_btn.OnPressedState.IconLeftImage = null;
            this.Pay_btn.OnPressedState.IconRightImage = null;
            this.Pay_btn.Size = new System.Drawing.Size(360, 129);
            this.Pay_btn.TabIndex = 5;
            this.Pay_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Pay_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Pay_btn.TextMarginLeft = 0;
            this.Pay_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Pay_btn.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel7
            // 
            this.bunifuPanel7.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel7.BackgroundImage")));
            this.bunifuPanel7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.bunifuPanel7.BorderRadius = 3;
            this.bunifuPanel7.BorderThickness = 0;
            this.bunifuPanel7.Controls.Add(this.pictureBox1);
            this.bunifuPanel7.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel7.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel7.Name = "bunifuPanel7";
            this.bunifuPanel7.ShowBorders = true;
            this.bunifuPanel7.Size = new System.Drawing.Size(360, 157);
            this.bunifuPanel7.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pictureBox1.BackgroundImage")));
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(360, 157);
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // Payment_btn
            // 
            this.Payment_btn.AllowAnimations = true;
            this.Payment_btn.AllowMouseEffects = true;
            this.Payment_btn.AllowToggling = false;
            this.Payment_btn.AnimationSpeed = 200;
            this.Payment_btn.AutoGenerateColors = false;
            this.Payment_btn.AutoRoundBorders = false;
            this.Payment_btn.AutoSizeLeftIcon = true;
            this.Payment_btn.AutoSizeRightIcon = true;
            this.Payment_btn.BackColor = System.Drawing.Color.Transparent;
            this.Payment_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Payment_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Payment_btn.BackgroundImage")));
            this.Payment_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Payment_btn.ButtonText = "Payment";
            this.Payment_btn.ButtonTextMarginLeft = 0;
            this.Payment_btn.ColorContrastOnClick = 45;
            this.Payment_btn.ColorContrastOnHover = 45;
            this.Payment_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Payment_btn.CustomizableEdges = borderEdges4;
            this.Payment_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Payment_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Payment_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Payment_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Payment_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Payment_btn.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Payment_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.IconLeft = null;
            this.Payment_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Payment_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Payment_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Payment_btn.IconMarginLeft = 11;
            this.Payment_btn.IconPadding = 10;
            this.Payment_btn.IconRight = null;
            this.Payment_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Payment_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Payment_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Payment_btn.IconSize = 25;
            this.Payment_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Payment_btn.IdleBorderRadius = 0;
            this.Payment_btn.IdleBorderThickness = 0;
            this.Payment_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Payment_btn.IdleIconLeftImage = null;
            this.Payment_btn.IdleIconRightImage = null;
            this.Payment_btn.IndicateFocus = false;
            this.Payment_btn.Location = new System.Drawing.Point(0, 424);
            this.Payment_btn.Name = "Payment_btn";
            this.Payment_btn.OnDisabledState.BorderColor = System.Drawing.SystemColors.Control;
            this.Payment_btn.OnDisabledState.BorderRadius = 1;
            this.Payment_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Payment_btn.OnDisabledState.BorderThickness = 1;
            this.Payment_btn.OnDisabledState.FillColor = System.Drawing.SystemColors.Control;
            this.Payment_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.OnDisabledState.IconLeftImage = null;
            this.Payment_btn.OnDisabledState.IconRightImage = null;
            this.Payment_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.onHoverState.BorderRadius = 1;
            this.Payment_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Payment_btn.onHoverState.BorderThickness = 1;
            this.Payment_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.Payment_btn.onHoverState.IconLeftImage = null;
            this.Payment_btn.onHoverState.IconRightImage = null;
            this.Payment_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.Payment_btn.OnIdleState.BorderRadius = 1;
            this.Payment_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Payment_btn.OnIdleState.BorderThickness = 1;
            this.Payment_btn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Payment_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.OnIdleState.IconLeftImage = null;
            this.Payment_btn.OnIdleState.IconRightImage = null;
            this.Payment_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.OnPressedState.BorderRadius = 1;
            this.Payment_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Payment_btn.OnPressedState.BorderThickness = 1;
            this.Payment_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Payment_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.Control;
            this.Payment_btn.OnPressedState.IconLeftImage = null;
            this.Payment_btn.OnPressedState.IconRightImage = null;
            this.Payment_btn.Size = new System.Drawing.Size(363, 127);
            this.Payment_btn.TabIndex = 2;
            this.Payment_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Payment_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Payment_btn.TextMarginLeft = 0;
            this.Payment_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Payment_btn.UseDefaultRadiusAndThickness = true;
            // 
            // Flat_btn
            // 
            this.Flat_btn.AllowAnimations = true;
            this.Flat_btn.AllowMouseEffects = true;
            this.Flat_btn.AllowToggling = false;
            this.Flat_btn.AnimationSpeed = 200;
            this.Flat_btn.AutoGenerateColors = false;
            this.Flat_btn.AutoRoundBorders = false;
            this.Flat_btn.AutoSizeLeftIcon = true;
            this.Flat_btn.AutoSizeRightIcon = true;
            this.Flat_btn.BackColor = System.Drawing.Color.Transparent;
            this.Flat_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Flat_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Flat_btn.BackgroundImage")));
            this.Flat_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.ButtonText = "Flat Management";
            this.Flat_btn.ButtonTextMarginLeft = 0;
            this.Flat_btn.ColorContrastOnClick = 45;
            this.Flat_btn.ColorContrastOnHover = 45;
            this.Flat_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Flat_btn.CustomizableEdges = borderEdges5;
            this.Flat_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Flat_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Flat_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Flat_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Flat_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Flat_btn.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Flat_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.IconLeft = null;
            this.Flat_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Flat_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Flat_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Flat_btn.IconMarginLeft = 11;
            this.Flat_btn.IconPadding = 10;
            this.Flat_btn.IconRight = null;
            this.Flat_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Flat_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Flat_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Flat_btn.IconSize = 25;
            this.Flat_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Flat_btn.IdleBorderRadius = 0;
            this.Flat_btn.IdleBorderThickness = 0;
            this.Flat_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Flat_btn.IdleIconLeftImage = null;
            this.Flat_btn.IdleIconRightImage = null;
            this.Flat_btn.IndicateFocus = false;
            this.Flat_btn.Location = new System.Drawing.Point(0, 289);
            this.Flat_btn.Name = "Flat_btn";
            this.Flat_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.OnDisabledState.BorderRadius = 1;
            this.Flat_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.OnDisabledState.BorderThickness = 1;
            this.Flat_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.OnDisabledState.ForeColor = System.Drawing.SystemColors.Control;
            this.Flat_btn.OnDisabledState.IconLeftImage = null;
            this.Flat_btn.OnDisabledState.IconRightImage = null;
            this.Flat_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.onHoverState.BorderRadius = 1;
            this.Flat_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.onHoverState.BorderThickness = 1;
            this.Flat_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.Flat_btn.onHoverState.IconLeftImage = null;
            this.Flat_btn.onHoverState.IconRightImage = null;
            this.Flat_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.OnIdleState.BorderRadius = 1;
            this.Flat_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.OnIdleState.BorderThickness = 1;
            this.Flat_btn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Flat_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.OnIdleState.IconLeftImage = null;
            this.Flat_btn.OnIdleState.IconRightImage = null;
            this.Flat_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.OnPressedState.BorderRadius = 1;
            this.Flat_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.OnPressedState.BorderThickness = 1;
            this.Flat_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.Control;
            this.Flat_btn.OnPressedState.IconLeftImage = null;
            this.Flat_btn.OnPressedState.IconRightImage = null;
            this.Flat_btn.Size = new System.Drawing.Size(360, 129);
            this.Flat_btn.TabIndex = 1;
            this.Flat_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Flat_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Flat_btn.TextMarginLeft = 0;
            this.Flat_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Flat_btn.UseDefaultRadiusAndThickness = true;
            // 
            // Home_btn
            // 
            this.Home_btn.AllowAnimations = true;
            this.Home_btn.AllowMouseEffects = true;
            this.Home_btn.AllowToggling = false;
            this.Home_btn.AnimationSpeed = 200;
            this.Home_btn.AutoGenerateColors = false;
            this.Home_btn.AutoRoundBorders = false;
            this.Home_btn.AutoSizeLeftIcon = true;
            this.Home_btn.AutoSizeRightIcon = true;
            this.Home_btn.BackColor = System.Drawing.Color.Transparent;
            this.Home_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Home_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Home_btn.BackgroundImage")));
            this.Home_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.ButtonText = "Home";
            this.Home_btn.ButtonTextMarginLeft = 0;
            this.Home_btn.ColorContrastOnClick = 45;
            this.Home_btn.ColorContrastOnHover = 45;
            this.Home_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.Home_btn.CustomizableEdges = borderEdges6;
            this.Home_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Home_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Home_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Home_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Home_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Home_btn.Font = new System.Drawing.Font("Century", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Home_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.IconLeft = null;
            this.Home_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Home_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Home_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Home_btn.IconMarginLeft = 11;
            this.Home_btn.IconPadding = 10;
            this.Home_btn.IconRight = null;
            this.Home_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Home_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Home_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Home_btn.IconSize = 25;
            this.Home_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Home_btn.IdleBorderRadius = 0;
            this.Home_btn.IdleBorderThickness = 0;
            this.Home_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Home_btn.IdleIconLeftImage = null;
            this.Home_btn.IdleIconRightImage = null;
            this.Home_btn.IndicateFocus = false;
            this.Home_btn.Location = new System.Drawing.Point(0, 163);
            this.Home_btn.Name = "Home_btn";
            this.Home_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.OnDisabledState.BorderRadius = 1;
            this.Home_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.OnDisabledState.BorderThickness = 1;
            this.Home_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.OnDisabledState.ForeColor = System.Drawing.SystemColors.Control;
            this.Home_btn.OnDisabledState.IconLeftImage = null;
            this.Home_btn.OnDisabledState.IconRightImage = null;
            this.Home_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.onHoverState.BorderRadius = 1;
            this.Home_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.onHoverState.BorderThickness = 1;
            this.Home_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.onHoverState.ForeColor = System.Drawing.SystemColors.Control;
            this.Home_btn.onHoverState.IconLeftImage = null;
            this.Home_btn.onHoverState.IconRightImage = null;
            this.Home_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.OnIdleState.BorderRadius = 1;
            this.Home_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.OnIdleState.BorderThickness = 1;
            this.Home_btn.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Home_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.OnIdleState.IconLeftImage = null;
            this.Home_btn.OnIdleState.IconRightImage = null;
            this.Home_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.OnPressedState.BorderRadius = 1;
            this.Home_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.OnPressedState.BorderThickness = 1;
            this.Home_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Home_btn.OnPressedState.IconLeftImage = null;
            this.Home_btn.OnPressedState.IconRightImage = null;
            this.Home_btn.Size = new System.Drawing.Size(360, 120);
            this.Home_btn.TabIndex = 0;
            this.Home_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Home_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Home_btn.TextMarginLeft = 0;
            this.Home_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Home_btn.UseDefaultRadiusAndThickness = true;
            // 
            // Flat_Management_Lessor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1582, 953);
            this.Controls.Add(this.bunifuPanel5);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Flat_Management_Lessor";
            this.Text = "Lessor";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel3.ResumeLayout(false);
            this.bunifuPanel3.PerformLayout();
            this.bunifuPanel5.ResumeLayout(false);
            this.tabControl1.ResumeLayout(false);
            this.bunifuPanel6.ResumeLayout(false);
            this.bunifuPanel4.ResumeLayout(false);
            this.bunifuPanel7.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton Setting_btn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton bunifuIconButton1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel5;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel6;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel2;
        private System.Windows.Forms.ComboBox comboBox2;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Chat_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Accept_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Pay_btn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel7;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Payment_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Flat_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Home_btn;
    }
}